languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Haocheng Wang"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"
  # mainSections = ["posts", "samples"]
  # description = "My awesome website"

[params.author]
  name = "Haocheng Wang"
  image = "img/avatar.jpg"
  headline = "Nice to meet you!"
  bio = "Die and live later"
  links = [
    { email = "1980250928@qq.com" },
    { github = "https://github.com/Rebornix-zero" },
    # { facebook = "https://facebook.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
  ]
